worker_processes  1;

events {
    worker_connections  1024;
}

http {

	include mime.types;
    default_type application/octet-stream;
	
    upstream uno {
        server 127.0.0.1:5010;
    }

    upstream api {
        server 127.0.0.1:5000;
    }

    upstream jellyfin {
        server 192.168.0.100:8096;
    }

    server {
        listen 80;
        server_name screeny.ddns.net;

		gzip on;
        gzip_types text/plain text/css application/javascript application/json application/wasm application/octet-stream;
        gzip_min_length 1000;
		
        # ─── Uno WASM ───
        location / {
            proxy_pass http://uno;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # ─── ApiGateway ───
        location /api/ {
            proxy_pass http://api;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # ─── Jellyfin HLS ───
        location ~* ^/proxy/hls/(.*)$ {
            set $target $1;
            proxy_pass http://jellyfin/$target$is_args$args;
            proxy_set_header X-Emby-Token "7061987c684e423ea59721c5ff8ca3a4";
            proxy_set_header Cookie "embyusertoken=7061987c684e423ea59721c5ff8ca3a4";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass_request_headers on;
            proxy_pass_request_body on;
        }
    }
}
